version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: simplecov
    versions:
    - 0.21.2
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: simplecov-console
    versions:
    - 0.9.0
    - 0.9.1
  rebase-strategy: disabled
